### ISSUE TITLE
cut/paste issue

### ISSUE THREAD

**Issue by ryanhar** [matthew-dean/Crunch#111]
When I cut text and then try to paste it somewhere else it will not paste the text. In order for it to work, I need to undo the cut and try to cut the text again and paste it in another place. So, on the first cut and paste it doesn't work, but undo and repeat cut and paste works fine. Using on Win7

**Comment by matthew-dean** [comment]
Hmm... couldn't replicate on Windows 8.1 w/ Crunch.

**Comment by ryanhar** [comment]
Since updating Crunch a little while ago, this isn't an issue for me anymore.

**Comment by matthew-dean** [comment]
Yay!
