### ISSUE TITLE
Crunch not compiling @imports, but not throwing error.

### ISSUE THREAD

**Issue by Melisunde** [matthew-dean/Crunch#115]
I'm using Bootstrap 3.3.2 and trying to crunch the bootstrap.less file (which is just filled with @imports.) I'll get the save dialog and my crunched css file will pop up with:

Line 1: /
Line 2: /

There would normally be little arrows next to the line numbers you could click on to see more, but there aren't in this case.

Any ideas? I've seen from past issues that occasionally Bootstrap will do something to throw a wrench in the works. I'm using Crunch version 1.9.3.

**Comment by matthew-dean** [comment]
Is the file actually empty? Are you currently minifying? If I recall correctly, there is a regression bug in 1.9.3 where very long lines in a file could not be displayed. Try opening the .css file in another editor and see if it has content, but simply isn't displaying.

**Comment by Melisunde** [comment]
That's exactly what was going on! Thank you.

**Comment by matthew-dean** [comment]
No problem! This will be addressed in the next major release.

**Comment by shareeneff** [comment]
I am using version 1.9.3 - and when I Crunch my .less file to .css..my css only shows 
/* CSS crunched with Crunch - http://crunchapp.net/ */

and the rest is blank. Please help!
