### ISSUE TITLE
Lack of functionality on Mac:

### ISSUE THREAD

**Issue by danjambur** [matthew-dean/Crunch#116]
Not retina supported
no option to remove unnecessary LESS files that don't need constant compiling.

**Comment by matthew-dean** [comment]
Can you explain your second item?

Retina will be addressed with the next major release of Crunch.

**Comment by danjambur** [comment]
Awesome, I look forward to using it, great stuff. Sorry I should've been more descriptive. Basically, when loading a CSS folder with the various folders and files, each and every LESS file in that list is compiled, although the changes I'd be making were to only one file. Will there be an option to remove the unnecessary files?

**Comment by matthew-dean** [comment]
I'm still not sure what you mean. In Crunch 1.x, and in Less in general, you only compile one file: the root. It wouldn't compile each and every Less file in a folder unless it was imported into that root e.g. ->
```
//root.less
@import "sub1.less";
@import "sub2.less";
```
The compiled file and output will be from compiling root.less and its included imports: sub1.less and sub2.less.

So I don't understand how it could be importing all of your less files unless all your less files were ```@import```ed.
