### ISSUE TITLE
Highlighted items within class

### ISSUE THREAD

**Issue by Pantyboy** [matthew-dean/Crunch#122]
Hello Matt and Matt (but mostly Matt).

I've checked through the help file but can find no reference to this.

If I have a class or ID and select a particular piece of information within that piece of code, all the over identical pieces of code appear highlighted.

For example, if I have a piece of code...
#gallery {
	columns:4;
	-webkit-columns:4; /* Safari and Chrome */
	-moz-columns:4; /* Firefox */
}
and I highlight the number 4 in the first line (columns:4), the other numbers 4 are highlighted (screenshot below).

Is this because there is a way to alter each highlighted instance with one keystroke or just an aid to remind me to alter the other instances?

Regards
Martin

![crunch-highlight](https://cloud.githubusercontent.com/assets/6214205/7463944/e85dcdee-f2b5-11e4-9e44-d927283c3e8f.jpg)

**Comment by matthew-dean** [comment]
That's been a feature in Ace (the embedded editor) for a long time, you just may have never noticed. It highlights other matches to your selection.
