### ISSUE TITLE
Avast Antivirus Warning when Live Update (March 13)

### ISSUE THREAD

**Issue by supakwong** [matthew-dean/Crunch#124]
Download update on March 13,2016 Cancel by Avast Antivirus Warning.

**Comment by matthew-dean** [comment]
Avast is apparently well-known for its rate of false-positives. There isn't anything I can do about that other than to suggest you use a different anti-virus program. See: http://www.thundercloud.net/infoave/new/dont-forget-to-check-your-antivirus-false-positives/

Closing as not a Crunch issue.
