### ISSUE TITLE
Auto-append file extension

### ISSUE THREAD

**Issue by hannesjohansson** [matthew-dean/Crunch#20]
Hey people!

Here's a feature suggestion:
When you are saving a file and no file extension the program should assume that it is a .less file that you're saving. What happens now is that it saves the file without an extension and then marks it as unsupported (which in turn unables you to open it).

Thanks for a great tool!

**Comment by matthew-dean** [comment]
Re-open on https://github.com/Crunch/Crunch-2/issues in the future if this pops up again as an issue.
