### ISSUE TITLE
Define root file

### ISSUE THREAD

**Issue by hillterence007** [matthew-dean/Crunch#24]
Hi,

it would be helpfull, if you add the option to select a less file as root (in "Folder-Mode"). i always have to switch to my main-file to compile.
Or is there a given naming i have to use?

Thx. Your doin a wonderfull job!

**Comment by matthew-dean** [comment]
Better late than never... Meaning I've already programmed this.

Actually, I should clarify to say that what's coming is far better than what you're asking for.
