### ISSUE TITLE
Open explorer at location of LESS source when selecting location of CSS output

### ISSUE THREAD

**Issue by adam-lynch** [matthew-dean/Crunch#36]
In Windows XP, I am brought to the Desktop when selecting the input and output.

**Comment by matthew-dean** [comment]
Adobe AIR has issues with setting default directories across all operating systems.

The next major release (which thankfully abandons Adobe AIR forever) will address this.

**Comment by matthew-dean** [comment]
This was originally a bug with Macs. Should be resolved in later versions of Crunch 1.x and in Crunch 2.x
