### ISSUE TITLE
Ommit WordPress theme style comment from minification

### ISSUE THREAD

**Issue by LucPestille** [matthew-dean/Crunch#39]
It would be very useful to be able to keep WordPress style theme comments at the top of the generated css - otherwise you have to remember what you've set them to, and manually go and put them back in once you've CRUNCH'd.

(With about 8 child themes for a particular network, that need updating at the same time, I can see this being a pain in the future...)

Thanks,

**Comment by matthew-dean** [comment]
I believe you can now do this with
```@import (inline) "wordpress-header.css"```
