### ISSUE TITLE
Features I would like to see

### ISSUE THREAD

**Issue by danwellman** [matthew-dean/Crunch#41]
As instructed, I'm raising an issue containing feature requests for things I think (after continued daily usage) would make the app even better. I'll keep adding to the list as I get more ideas.

I'm running Windows 7 and Crunch 1.5.3

1) Drag tabs to reorder - the tabs for each open file are draggable, but when you drop them, nothing happens. Make the tabs properly draggable!

2) Code completion - for both regular CSS and defined variables and mixins. Bonus points for intellisense-style tooltips showing the arguments accepted by mixins

3) Option to concatenate CSS files - e.g. when you hit crunch with several LESS files open you could compile to a single CSS file. You could add the files together in the order specified by the order of tabs?

Edit: 25/10/12
--------------------------------

4) A community area for pre-written mixins - allow users to upload mixins (with the ability for them to be rated maybe), and allow these to be downloaded from within the app. They could be used to build a library of snippets that could be dragged into a LESS file. I understand this is a massive feature, but it would be incredibly useful, and would help build a community around the app.

**Comment by matthew-dean** [comment]
I think I'm going to make a lot of people in this thread happy in the next few months...
