### ISSUE TITLE
Hide error dialog when crunch is clicked

### ISSUE THREAD

**Issue by adam-lynch** [matthew-dean/Crunch#45]
If you have an error, and you try to re-crunch but the error is the same, nothing happens visually. It's a bit confusing.

Option 1: On click of Crunch, remove the error dialog if it exists, then it'll be added by default anyway.
Option 2: When an error is returned, if the error dialog exists, make it flash in some way (reminiscent of the tabs on Crunch completion) or quickly disappear and reappear.

**Comment by matthew-dean** [comment]
This feature will be addressed in an upcoming version of Crunch.
