### ISSUE TITLE
Adobe AIR logo on website should link to AIR site ;)

### ISSUE THREAD

**Issue by amatecha** [matthew-dean/Crunch#48]
Small thing but, installing Crunch for the first time, on a machine without AIR, I automatically moused-over the AIR logo on the Crunch site, thinking it would link to the AIR download site.  This is more of a recommendation than an actual issue, but it would be useful for people who don't already have AIR installed :)

**Comment by matthew-dean** [comment]
Too small to consider before the next major release.
