### ISSUE TITLE
Crunchapp minifier

### ISSUE THREAD

**Issue by ghost** [matthew-dean/Crunch#51]
ver 1.5.3
Could you please add advanced settings to the Crunch minifier?

Options to omit ; (semicolon) at the the last property of the selector?

e.g.

button,input,select,textarea{font-family:inherit;font-size:100%;margin:0;}

to this

button,input,select,textarea{font-family:inherit;font-size:100%;margin:0}

see the omited semicolon, it saves some space :dancer:

**Comment by matthew-dean** [comment]
Less.js now has clean-css added as a plugin.
