### ISSUE TITLE
Error #3013

### ISSUE THREAD

**Issue by w00lly** [matthew-dean/Crunch#57]
Hi,
I tried using Crunch in combination with SimpLESS, so it auto-generates my style.css, when changing .less files, that get imported into the style.less. 
I noticed if I try to save changes too frequently, within 1 or 2 minutes, I get the following error:

"I failed in the saving of your glorious creation. Here's why: Error #3013"

Is there a way I can get rid of this error? Or will Crunch support this sort of auto-compiling when imported less files are saved in the future?

**Comment by matthew-dean** [comment]
I think this was an issue with other file operations locking files or keeping open handlers on files after updating, or something like that. My guess is Adobe AIR doesn't handle this gracefully, because Adobe AIR is a dick. Won't be fixed in 1.x. Will be less of a problem (or not a problem) in 2.x.
