### ISSUE TITLE
Compress compiled css?

### ISSUE THREAD

**Issue by sngan** [matthew-dean/Crunch#74]
Can we have a compress option in addition to the minify? (YUI-Compressor would be nice)

Thanks!

**Comment by matthew-dean** [comment]
Clean-css is now compatible with Less in the form of a plugin. Plugins will be supported in a future version of Crunch. http://lesscss.org/usage/#v2-upgrade-guide-clean-css

**Comment by sngan** [comment]
Okay, thanks.
