### ISSUE TITLE
Edit not working after crunch

### ISSUE THREAD

**Issue by trejster** [matthew-dean/Crunch#87]
Ive noticed an annoying issue, when a edit a file, save it then crunch the application. If i then go back to the file I was editing, I cannot edit it! I have to physically close the file then re-open it. It seems to only register backspace and cursor move

**Comment by matthew-dean** [comment]
This is still a sporadic issue in 1.x, but will be (and has been) addressed in the next major release of Crunch. In Crunch 1.x, you can also fix when this happens by selecting another tab with an editable file and coming back. It seems it was persisting the "readonly" state sometimes from the .css file.

**Comment by trejster** [comment]
Thankyou that's good to hear. I've moved over to Sass since the original
issue though I may revert back to less from the next crunch release

**Comment by matthew-dean** [comment]
Awesome. If you want to stay updated, follow at https://twitter.com/GetCrunch.
